DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    handle VARCHAR (32) NOT NULL,
    email VARCHAR (256) NOT NULL,
    passwordHash VARCHAR (256) NOT NULL
);
